[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.12"
pydantic = {extras = ["settings"], version = "^2.11.3"}
aiohttp = "^3.11.18"
pydantic-settings = "^2.9.1"
uvicorn = "^0.34.2"
async-lru = "^2.0.5"
